name: Issue 3.2 reproducer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Add explicit SAM constructor declaration
        if: always()
        run: |
          sed -i -e "s|{ value ->|SomeFunctionalInterface { value ->|g" src/main/kotlin/dev/monosoul/kotlin/samissue/3_Implementations.kt

      - name: Run the tests
        if: always()
        run: ./gradlew clean test
