name: Issue 2 reproducer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run the tests before the change
        run: ./gradlew clean test

      - name: Test report before the change
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          check_name: Test report before the change
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Remove @JvmInline annotation
        if: always()
        run: |
          sed -i -e "s|@JvmInline||g" src/main/kotlin/dev/monosoul/kotlin/samissue/SomeValueClass.kt

      - name: Change value class to data class annotation
        if: always()
        run: |
          sed -i -e "s|value class|data class|g" src/main/kotlin/dev/monosoul/kotlin/samissue/SomeValueClass.kt

      - name: Run the tests after the change
        if: always()
        run: ./gradlew clean test

      - name: Test report after the change
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          check_name: Test report after the change
          report_paths: '**/build/test-results/**/TEST-*.xml'
